# Generated by Django 5.2.4 on 2025-07-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(max_length=500, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
