# Generated by Django 5.2.4 on 2025-07-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
