# Generated by Django 5.2.4 on 2025-07-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Loginss',
        ),
    ]
