# Generated by Django 5.2.4 on 2025-07-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_login_loginss'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginss',
            name='age',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
