# Generated by Django 5.2.4 on 2025-07-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_loginss_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginss',
            name='age',
        ),
    ]
