# Generated by Django 5.2.4 on 2025-07-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('rate', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
